In [1]:
import pandas as pd
data=pd.read_csv("Sales_Data_Challenges.csv")
data.head()

,OrderID,Category,City,PaymentMethod,SaleDate,Price,Quantity,Discount,Revenue
0,ORD-7778,Furniture,Houston,Debit Card,2024-06-24,610.101338,1.0,20,488.08
1,ORD-6791,Furniture,Chicago,NaN,2024-05-02,714.329017,30.0,48,11143.53
2,ORD-6138,Stationery,New York,Credit Card,2024-01-07,761.840755,46.0,18,28736.63
3,ORD-8291,Furniture,New York,Credit Card,2024-06-27,564.990275,37.0,18,17141.80
4,ORD-1314,Appliances,Houston,Credit Card,2024-02-09,771.496793,30.0,11,20598.96

In [2]:
# 1. Calculate the total revenue generated by each city
total_revenue_by_city = data.groupby('City')['Revenue'].sum()
total_revenue_by_city

City
Chicago        1459850.70
Houston        1583426.63
Los Angeles    1735146.79
New York       1120128.43
Phoenix        1564476.88
Name: Revenue, dtype: float64

In [3]:
# 2. Identify the category with the highest sales and most significant contribution to total revenue
category_summary = data.groupby('Category')[['Revenue', 'Quantity']].sum().sort_values(by='Revenue')
category_summary

                Revenue  Quantity
Category
Furniture    1341636.11    3827.0
Electronics  1402616.99    4340.0
Appliances   1512419.78    4193.0
Stationery   1602198.83    3715.0
Clothing     1604157.72    4642.0

In [4]:
# 3. Find products with frequent sales discrepancies (e.g., high discount percentages, missing prices)
sales_discrepancies= data[(data['Price'].isna()) | (data['Discount'] > 70)]
print(sales_discrepancies.shape)
sales_discrepancies

(39, 9)

,OrderID,Category,City,PaymentMethod,SaleDate,Price,Quantity,Discount,Revenue
16,ORD-8700,Furniture,New York,Cash,2024-04-22,NaN,43.0,4,NaN
55,ORD-8046,Electronics,Chicago,NaN,2024-01-17,NaN,41.0,42,NaN
59,ORD-8867,Electronics,Houston,Cash,2024-03-19,NaN,9.0,8,NaN
114,ORD-1524,Appliances,Phoenix,NaN,2024-03-27,NaN,3.0,2,NaN
118,ORD-2582,Clothing,Chicago,NaN,2024-02-02,NaN,36.0,49,NaN
137,ORD-1133,Electronics,Los Angeles,Cash,2024-02-14,NaN,38.0,2,NaN
144,ORD-7323,Stationery,Phoenix,NaN,2024-03-25,NaN,NaN,26,NaN
179,ORD-1001,Electronics,Phoenix,Debit Card,NaN,NaN,46.0,2,NaN
201,ORD-1415,Stationery,Houston,Online Payment,2024-05-09,NaN,27.0,20,NaN
211,ORD-7002,Stationery,Phoenix,Credit Card,2024-02-05,NaN,39.0,27,NaN
213,ORD-4362,Appliances,Houston,Cash,2024-01-11,NaN,-4.0,22,NaN
222,ORD-2644,Clothing,Chicago,Credit Card,2024-02-24,NaN,11.0,2,NaN
223,ORD-5111,Electronics,Phoenix,NaN,2024-05-19,NaN,7.0,10,NaN
231,ORD-7965,Clothing,Houston,Cash,2024-04-05,NaN,47.0,12,NaN
248,ORD-3899,Furniture,Houston,Credit Card,2024-05-21,NaN,49.0,25,NaN
249,ORD-2681,Clothing,Los Angeles,Debit Card,2024-05-24,NaN,10.0,35,NaN
294,ORD-6078,Clothing,Houston,Online Payment,2024-01-11,NaN,49.0,49,NaN
319,ORD-7019,Electronics,Los Angeles,Cash,2024-01-12,NaN,NaN,20,NaN
347,ORD-7423,Furniture,Phoenix,Cash,2024-05-15,NaN,-13.0,30,NaN
358,ORD-4530,Clothing,Chicago,Cash,2024-02-15,NaN,50.0,44,NaN
362,ORD-9956,Clothing,New York,NaN,2024-06-23,NaN,19.0,20,NaN
370,ORD-1483,Electronics,Los Angeles,Debit Card,2024-06-10,NaN,40.0,14,NaN
378,ORD-9731,Furniture,Los Angeles,Debit Card,2024-04-21,NaN,32.0,2,NaN
401,ORD-4089,Electronics,Houston,Debit Card,2024-06-29,NaN,1.0,7,NaN
481,ORD-1759,Electronics,Los Angeles,Debit Card,2024-06-04,NaN,36.0,39,NaN
487,ORD-7326,Appliances,New York,Credit Card,2024-03-10,NaN,35.0,4,NaN
500,ORD-6191,Furniture,Los Angeles,NaN,2024-01-21,NaN,40.0,39,NaN
508,ORD-9994,Furniture,Chicago,Credit Card,NaN,NaN,NaN,9,NaN
708,ORD-4153,Electronics,New York,NaN,2024-04-13,NaN,37.0,16,NaN
712,ORD-1354,Appliances,Houston,NaN,2024-02-11,NaN,6.0,36,NaN
724,ORD-3559,Electronics,New York,Online Payment,2024-05-01,NaN,27.0,49,NaN
796,ORD-7899,Stationery,Phoenix,NaN,2024-05-10,NaN,29.0,44,NaN
797,ORD-1476,Appliances,Phoenix,Debit Card,2024-04-12,NaN,36.0,44,NaN
805,ORD-4873,Electronics,Phoenix,NaN,2024-01-16,NaN,48.0,32,NaN
836,ORD-1189,Appliances,Houston,Online Payment,2024-02-24,NaN,22.0,0,NaN
885,ORD-5909,Appliances,Los Angeles,Debit Card,2024-02-16,NaN,40.0,22,NaN
932,ORD-2197,Clothing,Chicago,NaN,2024-05-14,NaN,28.0,7,NaN
945,ORD-7064,Clothing,Los Angeles,Online Payment,NaN,NaN,22.0,30,NaN
978,ORD-1516,Clothing,New York,Online Payment,2024-03-07,NaN,46.0,39,NaN

In [5]:
# 4. Identify the most preferred payment method
preferred_payment_method = data['PaymentMethod'].value_counts()
preferred_payment_method

PaymentMethod
Online Payment    205
Debit Card        200
Cash              198
Credit Card       179
Name: count, dtype: int64

In [6]:
# 5.Check for cities with bias toward specific payment methods
city_payment_bias = data.groupby(['City', 'PaymentMethod']).size().unstack(fill_value=0)
city_payment_bias

PaymentMethod  Cash  Credit Card  Debit Card  Online Payment
City
Chicago          45           34          43              29
Houston          39           41          42              53
Los Angeles      46           31          46              39
New York         28           34          30              41
Phoenix          40           39          39              43